<<<<<<< HEAD
import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner";
=======
// app/layout.tsx (Server Component)

import type { Metadata } from "next"
import "./globals.css"
import Providers from "./providers"  // 아래 2)에서 만드는 파일
>>>>>>> c350f983adaabd5b47b386329954a82136268f6f

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
<<<<<<< HEAD
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Header/>
          <div className="flex min-h-screen">
            <Sidebar/>
            <div className="flex-1 p-4 bg-gray-100 overflow-y-auto scrollbar-hide">
              {children}
            </div>
          </div>

          <Toaster position="top-center"/>
        </body> 
      </html>
    </ClerkProvider>
  );
=======
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* 2)에서 만든 클라이언트 Providers로 감싸주기 */}
        <Providers>{children}</Providers>
      </body>
    </html>
  )
>>>>>>> c350f983adaabd5b47b386329954a82136268f6f
}
