// app/layout.tsx (Server Component)

import type { Metadata } from "next"
import "./globals.css"
import Providers from "./providers"  // 아래 2)에서 만드는 파일

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* 2)에서 만든 클라이언트 Providers로 감싸주기 */}
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
